force-app/main/default/objects/Location_event__c/Location_event__c.object-meta.xml
<CustomObject>
    <label>Location(event)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location(event)s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_event__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_event__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LocationAddressQueueable.cls
public class LocationAddressQueueable
implements Queueable, Database.AllowsCallouts {
    
    private Set<Id> locationIds;
    
    public LocationAddressQueueable(Set<Id> locationIds) {
        this.locationIds = locationIds;
    }
    
    public void execute(QueueableContext qc) {
        
        List<Location_event__c> locations = [SELECT Id, Street__c, City__c, State__c, Postal_Code__c FROM Location_event__c WHERE Id IN :locationIds];
        
        List<Location_event__c> updates = new List<Location_event__c>();
        
        for (Location_event__c loc : locations) {
                Boolean verified = NominatimLocationService.verifyAddress(
                loc.Street__c,
                loc.City__c,
                loc.State__c,
                loc.Postal_Code__c
            );
            
            
            updates.add(new Location_event__c(
                Id = loc.Id,
                Verified__c = verified
            ));
        }
        
        if (!updates.isEmpty()) {
            update updates;
        }
    }
}