force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorHandler.cls
public class ErrorHandler {

    public static void logError(
        String processName,
        Exception e
    ) {
        try {
            Error_Log__c errorLog = new Error_Log__c();
            errorLog.Process_Name__c = processName;
            errorLog.Log_Details__c = e.getMessage();
            
            errorLog.Log__c = System.now();

            insert errorLog;
        } catch (Exception ex) {
            // Avoid infinite loop
            System.debug('Error while logging error: ' + ex.getMessage());
        }
    }
}