force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendeess</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event_Mng__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Mng__c/Event_Mng__c.object-meta.xml
<CustomObject>
    <label>Event-Mng</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Mngs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Mng__c/fields/Location_event__c.field-meta.xml
<CustomField>
    <fullName>Location_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location(event)</label>
    <referenceTo>Location_event__c</referenceTo>
    <relationshipLabel>Event-Mngs</relationshipLabel>
    <relationshipName>Event_Mngs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Mng__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Mng__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Mng__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Post Poned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_event__c/Location_event__c.object-meta.xml
<CustomObject>
    <label>Location(event)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location(event)s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHandler_Test.cls
@IsTest
public class EventAttendeeTriggerHandler_Test {
    
    @IsTest
    static void test_sendConfirmationEmail_method() {
        
        
        // Create Organizer
        
        Event_Organizer__c organizer = new Event_Organizer__c(
            Name = 'Test Organizer'
        );
        insert organizer;
        
        
        //  Create Location
        
        Location_event__c location = new Location_event__c(
            Name = 'Pune'
        );
        insert location;
        
        
        //  Create Event (required fields only)
        
        Event_Mng__c eventRec = new Event_Mng__c(
            Name__c = 'Unit Test Event',
            Start__c = System.now().addDays(1),
            Location_event__c = location.Id,
            Organizer__c = organizer.Id,
            Live__c = true,
            Status__c = 'Completed',
            Max_Seats__c = 100
        );
        insert eventRec;
        
        
        //  Create Attendee (WITH email)
        
        Attendees__c attendee = new Attendees__c(
            Name = 'Rahul',
            Email__c = 'rahul@test.com',
            Phone__c = '9999999999'
        );
        insert attendee;
        
        
        // Create Event_Attendee record
        
        Event_Attendee__c ea = new Event_Attendee__c(
            Name = 'EA-UNIT',
            Event__c = eventRec.Id,
            Attendees__c = attendee.Id
        );
        insert ea;
        
        
        // DIRECT METHOD CALL
        
        List<Event_Attendee__c> eaList =
            [SELECT Id, Event__c, Attendees__c
             FROM Event_Attendee__c
             WHERE Id = :ea.Id];
        
        Test.startTest();
        EventAttendeeTriggerHandler.sendConfirmationEmail(eaList);
        Test.stopTest();
        
        
        // Assertion (method executed)
        
        System.assertEquals(
            1,
            eaList.size(),
            'Handler method executed successfully'
        );
    }
}