force-app/main/default/objects/Event_Mng__c/Event_Mng__c.object-meta.xml
<CustomObject>
    <label>Event-Mng</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Mngs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Mng__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OldEventCleanupBatch.cls
public class OldEventCleanupBatch
    implements Database.Batchable<SObject>, Database.Stateful {
    public Integer totalDeleted = 0;    
    // start() – old events fetch    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date twoMonthsAgo = System.today().addMonths(-2);
        return Database.getQueryLocator([SELECT Id FROM Event_Mng__c WHERE End__c < :twoMonthsAgo AND Organizer__c != null] );
    }   
    // execute() – delete logic    
    public void execute(Database.BatchableContext bc, List<Event_Mng__c> scope) {
        totalDeleted += scope.size();
        OldEventCleanupHandler.deleteEvents(scope);
    }   
    // finish() – confirmation email    
    public void finish(Database.BatchableContext bc) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new List<String>{ 'suhaiv@zebratechnosys.com ' });
        mail.setSubject('Batch Execution Completed');
        mail.setPlainTextBody('Old Event Cleanup Batch completed successfully.\n\n' +'Total Events Deleted: ' + totalDeleted + '\n' +'Completed On: ' + System.now()
        );
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail }
        );
    }
}